version: '3'
services:
  atte_tech_config_bot:
    build: .
    container_name: atte_tech_config_bot
    restart: unless-stopped
    secrets:
      - TELEGRAM_BOT_TOKEN
      - API_URL
      - API_USERNAME
      - API_PASSWORD
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  TELEGRAM_BOT_TOKEN:
    external: true
  API_URL:
    external: true
  API_USERNAME:
    external: true
  API_PASSWORD:
    external: true
